# Specifying the source repository to the argocd, so it can be synced, and destination
# server addr so, it can provision those resources it finds in the git repo.
# Also we are specifying the policy of auto synced,

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bharatmicrosystems/argo-cd-example.git
    targetRevision: HEAD
    path: manifests/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
